-- Insertar 8 protectoras
INSERT IGNORE INTO protectors (photo, name, username, password, description, phone, email, city, province, web_site) VALUES
('http://localhost:8080/images/AdoptaUnAmigo.jpg', 'AdoptaUnAmigo', 'adopta_un_amigo', 'SecurePassword1', 'Nos dedicamos a encontrar hogares para animales rescatados.', '654321987', 'info@adoptaunamigo.com', 'Madrid', 'Madrid', 'https://adoptaunamigo.com'),
('http://localhost:8080/images/HuellasDeAmor.jpg', 'Huellas de Amor', 'huellas_de_amor', 'SecurePassword2', 'Brindamos amor y cuidado a los animales abandonados.', '612345678', 'contacto@huellasdeamor.org', 'Barcelona', 'Cataluña', 'https://huellasdeamor.org'),
('http://localhost:8080/images/PatasAlmas.jpg', 'Patas y Almas', 'patas_y_almas', 'SecurePassword3', 'Luchamos por el bienestar de nuestros amigos de cuatro patas.', '698765432', 'info@patasyalmas.org', 'Valencia', 'Comunidad Valenciana', 'https://patasyalmas.org'),
('http://localhost:8080/images/RefugioEsperanza.jpg', 'Refugio Esperanza', 'refugio_esperanza', 'SecurePassword4', 'Damos refugio a los animales que lo necesitan.', '612345679', 'info@refugioesperanza.com', 'Sevilla', 'Andalucía', 'https://refugioesperanza.com'),
('http://localhost:8080/images/FundacionPeluditos.jpg', 'Fundación Peluditos', 'fundacion_peluditos', 'SecurePassword5', 'Rescatamos y cuidamos a los peluditos en necesidad.', '698765431', 'contacto@fundacionpeluditos.org', 'Bilbao', 'País Vasco', 'https://fundacionpeluditos.org'),
('http://localhost:8080/images/AmigosSinHogar.jpg', 'Amigos Sin Hogar', 'amigos_sin_hogar', 'SecurePassword6', 'Un refugio seguro para los animales olvidados.', '612345680', 'info@amigossinhogar.com', 'Alicante', 'Comunidad Valenciana', 'https://amigossinhogar.com'),
('http://localhost:8080/images/SosAnimales.jpg', 'SOS Animales', 'sos_animales', 'SecurePassword7', 'Salvando vidas, una pata a la vez.', '698765430', 'contact@sosanimales.org', 'Granada', 'Andalucía', 'https://sosanimales.org'),
('http://localhost:8080/images/PatitasLibres.jpg', 'Patitas Libres', 'patitas_libres', 'SecurePassword8', 'Promovemos la adopción y el bienestar animal.', '654321986', 'info@patitaslibres.com', 'Murcia', 'Región de Murcia', 'https://patitaslibres.com');
